import { TCAHORARIOSC } from '@prisma/client'

export function InitClassScheduleService(
  idMatrix: number,
  codPeriod: number
): TCAHORARIOSC {
  return {
    TCAHORARIOSC_ID: 0,
    TCAMATRICES_ID: idMatrix,
    TCAHORARIOSC_COD_CARRERA: '',
    TCAHORARIOSC_PERIODO: codPeriod,
    TCAHORARIOSC_NRC: 0,
    TCAHORARIOSC_ASIGNATURA: '',
    TCAHORARIOSC_TIPO: 'Clase',
    TCAHORARIOSC_LUNES_ENTRADA: '--:--',
    TCAHORARIOSC_LUNES_SALIDA: '--:--',
    TCAHORARIOSC_AULA_LUNES: '',
    TCAHORARIOSC_MARTES_ENTRADA: '--:--',
    TCAHORARIOSC_MARTES_SALIDA: '--:--',
    TCAHORARIOSC_AULA_MARTES: '',
    TCAHORARIOSC_MIERCOLES_ENTRADA: '--:--',
    TCAHORARIOSC_MIERCOLES_SALIDA: '--:--',
    TCAHORARIOSC_AULA_MIERCOLES: '',
    TCAHORARIOSC_JUEVES_ENTRADA: '--:--',
    TCAHORARIOSC_JUEVES_SALIDA: '--:--',
    TCAHORARIOSC_AULA_JUEVES: '',
    TCAHORARIOSC_VIERNES_ENTRADA: '--:--',
    TCAHORARIOSC_VIERNES_SALIDA: '--:--',
    TCAHORARIOSC_AULA_VIERNES: '',
  }
}
