import type { TCAHORARIOST } from '@prisma/client'

export interface WorkSchedule {
  TCAHORARIOST_ID: number
  TCAMATRICES_ID: number
  TCAHORARIOST_JORNADA: string
  TCAHORARIOST_LUNES_INGRESO: string | null
  TCAHORARIOST_LUNES_SALIDA: string | null
  TCAHORARIOST_LUNES_BIOMETRICO: string
  TCAHORARIOST_MARTES_INGRESO: string | null
  TCAHORARIOST_MARTES_SALIDA: string | null
  TCAHORARIOST_MARTES_BIOMETRICO: string
  TCAHORARIOST_MIERCOLES_INGRESO: string | null
  TCAHORARIOST_MIERCOLES_SALIDA: string | null
  TCAHORARIOST_MIERCOLES_BIOMETRICO: string
  TCAHORARIOST_JUEVES_INGRESO: string | null
  TCAHORARIOST_JUEVES_SALIDA: string | null
  TCAHORARIOST_JUEVES_BIOMETRICO: string
  TCAHORARIOST_VIERNES_INGRESO: string | null
  TCAHORARIOST_VIERNES_SALIDA: string | null
  TCAHORARIOST_VIERNES_BIOMETRICO: string
}

export function morningRow(idMatrix: number): TCAHORARIOST {
  return {
    TCAHORARIOST_ID: 0,
    TCAMATRICES_ID: idMatrix,
    TCAHORARIOST_JORNADA: 'Matutina',
    TCAHORARIOST_LUNES_INGRESO: '--:--',
    TCAHORARIOST_LUNES_SALIDA: '--:--',
    TCAHORARIOST_LUNES_BIOMETRICO: 'F',
    TCAHORARIOST_MARTES_INGRESO: '--:--',
    TCAHORARIOST_MARTES_SALIDA: '--:--',
    TCAHORARIOST_MARTES_BIOMETRICO: 'F',
    TCAHORARIOST_MIERCOLES_INGRESO: '--:--',
    TCAHORARIOST_MIERCOLES_SALIDA: '--:--',
    TCAHORARIOST_MIERCOLES_BIOMETRICO: 'F',
    TCAHORARIOST_JUEVES_INGRESO: '--:--',
    TCAHORARIOST_JUEVES_SALIDA: '--:--',
    TCAHORARIOST_JUEVES_BIOMETRICO: 'F',
    TCAHORARIOST_VIERNES_INGRESO: '--:--',
    TCAHORARIOST_VIERNES_SALIDA: '--:--',
    TCAHORARIOST_VIERNES_BIOMETRICO: 'F',
  }
}

export function afternoonRow(idMatrix: number): TCAHORARIOST {
  return {
    TCAHORARIOST_ID: 0,
    TCAMATRICES_ID: idMatrix,
    TCAHORARIOST_JORNADA: 'Vespertina',
    TCAHORARIOST_LUNES_INGRESO: '--:--',
    TCAHORARIOST_LUNES_SALIDA: '--:--',
    TCAHORARIOST_LUNES_BIOMETRICO: 'F',
    TCAHORARIOST_MARTES_INGRESO: '--:--',
    TCAHORARIOST_MARTES_SALIDA: '--:--',
    TCAHORARIOST_MARTES_BIOMETRICO: 'F',
    TCAHORARIOST_MIERCOLES_INGRESO: '--:--',
    TCAHORARIOST_MIERCOLES_SALIDA: '--:--',
    TCAHORARIOST_MIERCOLES_BIOMETRICO: 'F',
    TCAHORARIOST_JUEVES_INGRESO: '--:--',
    TCAHORARIOST_JUEVES_SALIDA: '--:--',
    TCAHORARIOST_JUEVES_BIOMETRICO: 'F',
    TCAHORARIOST_VIERNES_INGRESO: '--:--',
    TCAHORARIOST_VIERNES_SALIDA: '--:--',
    TCAHORARIOST_VIERNES_BIOMETRICO: 'F',
  }
}

export interface CellMondayProps {
  TCAHORARIOST_ID: number
  TCAHORARIOST_LUNES_INGRESO: string
  TCAHORARIOST_LUNES_SALIDA: string
  TCAHORARIOST_LUNES_BIOMETRICO: string
}

export interface CellTuesdayProps {
  TCAHORARIOST_ID: number
  TCAHORARIOST_MARTES_INGRESO: string
  TCAHORARIOST_MARTES_SALIDA: string
  TCAHORARIOST_MARTES_BIOMETRICO: string
}

export interface CellWednesdayProps {
  TCAHORARIOST_ID: number
  TCAHORARIOST_MIERCOLES_INGRESO: string
  TCAHORARIOST_MIERCOLES_SALIDA: string
  TCAHORARIOST_MIERCOLES_BIOMETRICO: string
}

export interface CellThursdayProps {
  TCAHORARIOST_ID: number
  TCAHORARIOST_JUEVES_INGRESO: string
  TCAHORARIOST_JUEVES_SALIDA: string
  TCAHORARIOST_JUEVES_BIOMETRICO: string
}

export interface CellFridayProps {
  TCAHORARIOST_ID: number
  TCAHORARIOST_VIERNES_INGRESO: string
  TCAHORARIOST_VIERNES_SALIDA: string
  TCAHORARIOST_VIERNES_BIOMETRICO: string
}

export type DayProps =
  | CellMondayProps
  | CellTuesdayProps
  | CellWednesdayProps
  | CellThursdayProps
  | CellFridayProps

export type Days = 'LUNES' | 'MARTES' | 'MIERCOLES' | 'JUEVES' | 'VIERNES'
